version: "3.3"
services:
  ddos-detection:
    image: "${REGISTRY}/ddos-detection"
    container_name: ddos-detection
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    network_mode: "host"