{{- if .Values.sample.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: {{ required "Need to specify the image registry" .Values.imageRegistry }}/nodeserver 
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
{{- end }}