#Required: A registry where to pull app images
#Example:
#imageRegistry: "<REGISTRY-IP>:<REGISTRY-PORT>"
#You add option to helm install command like this
#--set imageRegistry="<REGISTRY-IP>:<REGISTRY-PORT>"

sample:
  app:
    enabled: false
  pythonMachine:
    enabled: false
  user:
    enabled: false
    replicas: 3

preConfiguration:
  enabled: true

redis:
  enabled: true
    

ddosDetector:
  enabled: true
  replicas: 1

executor:
  enabled: true

scraper:
  enabled: true

kddui:
  enabled: true
  service:
    type: NodePort
    nodePort: 32080