apiVersion: v1
kind: ServiceAccount
metadata:
  name: kdd-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdd-admin
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["cilium.io"]
  resources: ["ciliumclusterwidenetworkpolicies"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kdd-admin
subjects:
- kind: ServiceAccount
  name: kdd-admin # case sensitive
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: kdd-admin
  apiGroup: "rbac.authorization.k8s.io"
