version: "3.3"
services:
  ddos-detection:
    image: 192.168.56.1:5000/python-attacker
    container_name: python-attacker
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    network_mode: "host"