version: "3.3"
services:
  python-attacker:
    image: "${REGISTRY}/python-attacker"
    container_name: python-attacker
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    network_mode: "host"