version: "3.3"
services:
  normal-user:
    image: "${REGISTRY}/normal-user"
    container_name: normal-user
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    network_mode: "host"