version: "3.3"
services:
  executor:
    image: "${REGISTRY}/kdd-executor"
    container_name: kdd-executor
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    network_mode: "host"