apiVersion: v1
kind: Service
metadata:
  name: kddui
spec:
  selector:
    kdd-component: kddui
  type: NodePort
  ports:
   - port: 7080
     nodePort: 32080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kddui
  labels:
    kdd-component: kddui
spec:
  replicas: 1
  selector:
    matchLabels:
      kdd-component: kddui
  template:
    metadata:
      labels:
        kdd-component: kddui
    spec:
      serviceAccountName: kdd-admin
      containers:
      - name: kddui
        image: 192.168.56.1:5000/kddui
        imagePullPolicy: Always
