apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdd-admin
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["cilium.io"]
  resources: ["ciliumclusterwidenetworkpolicies"]
  verbs: ["get", "watch", "list", "create"]