{{- if .Values.kddui.deprecated.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdd-ui
  namespace: kube-system
  labels:
    kdd-component: kdd-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      kdd-component: kdd-ui
  template:
    metadata:
      labels:
        kdd-component: kdd-ui
    spec:
      serviceAccountName: kdd-admin
      containers:
      - name: kdd-ui
        image: {{ required "Need to specify the image registry" .Values.imageRegistry }}/kdd-ui
        imagePullPolicy: Always
{{- end }}