{{- if .Values.ddosDetector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdd-ddos-detector
  namespace: kube-system
  labels:
    module: kdd-ddos-detector
spec:
  replicas: {{ .Values.ddosDetector.replicas }}
  selector:
    matchLabels:
      module: kdd-ddos-detector
  template:
    metadata:
      labels:
        module: kdd-ddos-detector
    spec:
      containers:
      - name: kdd-ddos-detector
        image: {{ required "Need to specify the image registry" .Values.imageRegistry }}/kdd-ddos-detector
        imagePullPolicy: Always
{{- end }}