{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdd-redis
  namespace: kube-system
  labels:
    module: kdd-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      module: kdd-redis
  template:
    metadata:
      labels:
        module: kdd-redis
    spec:
      containers:
      - name: kdd-redis
        image: redis:5.0.4
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: kdd-redis-config
            items:
            - key: redis-config
              path: redis.conf
{{- end }}