apiVersion: v1
kind: Service
metadata:
  name: kddui
  namespace: kube-system
spec:
  selector:
    kdd-component: kddui
  type: NodePort
  ports:
   - port: 7080
     nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kube-system
spec:
  selector:
    module: redis
  type: NodePort
  ports:
  - port: 6379
    nodePort: 31079
{{- if .Values.targetApp.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
   - port: 5050
     nodePort: 32000
{{- end }}