version: "3.3"
services:
  nodeserver:
    image: "${REGISTRY}/nodeserver"
    container_name: nodeserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 5050:5050
    network_mode: "host"