apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  labels:
    kdd-component: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      kdd-component: scraper
  template:
    metadata:
      labels:
        kdd-component: scraper
    spec:
      serviceAccountName: kdd-admin
      containers:
      - name: scraper
        image: 192.168.56.1:5000/scraper
        imagePullPolicy: Always
